source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use sqlite3 as the database for Active Record
# gem "sqlite3", ">= 2.1"
gem "pg"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

gem "rubocop-rails-omakase", require: false, group: [ :development ]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

# ----------------------------------------------- OpenTelemetry

# Traces
gem "opentelemetry-sdk", "~> 1.12"
gem "opentelemetry-exporter-otlp", "~> 0.34.0"
gem "opentelemetry-instrumentation-all", "~> 0.94.0"

# Metrics
gem "opentelemetry-metrics-sdk"
gem "opentelemetry-exporter-otlp-metrics"

# Logs
gem "opentelemetry-logs-sdk"
gem "opentelemetry-exporter-otlp-logs"
gem "opentelemetry-instrumentation-logger"

# # Profiling
gem 'pyroscope'
gem 'pyroscope-otel'

