default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'otel_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "otel_test#{ENV['TEST_ENV_NUMBER']}" } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>

production:
  <<: *default
